// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Rocky_DataAccess.Data;

namespace Rocky_DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext)), Migration("20210529153000_addFullNameToUsersTable")]
    internal class addFullNameToUsersTableBase : addFullNameToUsersTableBaseBase
    {
    }
}